from moeda import *
print('=-' * 41)
print('-' * 34, 'EXERCÍCIO 109', '-' * 33)
print('-' * 27, 'Formatando Moedas em Python', '-' * 26)
print('=-' * 41)
n = float(input('Digite o preço: R$'))
print(f'A metade de {moeda(n)} é {metade(n, True)}')
print(f'O dobro de {moeda(n)} é {dobro(n, True)}')
print(f'Aumentando {moeda(10)}%, temos {aumentar(n, 10, True)}')
print(f'Reduzindo {moeda(13)}%, temos {diminuir(n, 13, True)}')
