""" Cadeia de caracteres"""
f = '   Frase de teste para a aula   '
print(f)
print('A frase {} possui {} caracteres.'.format(f, len(f)))
c = input('Digite uma letra: ')
print('A frase: "{}", possui {} letras "{}".'.format(f, f.count(c), c))
c = input('Digite um ou mais caracteres: ')
print('A letra ou palavra começa na posição {}'.format(f.find(c)))
c = input('Digite uma letra novamente: ')
print('A existência da letra "{}" na frase é: {}'.format(c, c in f))
c = input('Digite uma letra ou palavra para substituir "Frase" em:\n "   Frase de teste para a aula   ": ')
f = f.replace('Frase', c)
print('Frase atual: {}.'.format(f))
print('Frase em maiúsculo: {}.'.format(f.upper()))
print('Frase em maiúsculo: {}.'.format(f.lower()))
print('Frase em titulo: {}.'.format(f.title()))
print('Frase sem espaços em branco no início e fim: {}.'.format(f.strip()))
print('Frase sem espaços em branco no fim: {}.'.format(f.rstrip()))
print('Frase sem espaços em branco no início: {}.'.format(f.lstrip()))
f = f.strip()
print('Frase capitalizada: {}.'.format(f.capitalize()))
