from moeda import *
print('=-' * 41)
print('-' * 34, 'EXERCÍCIO 109', '-' * 33)
print('-' * 27, 'Formatando Moedas em Python', '-' * 26)
print('=-' * 41)
n = float(input('Digite o preço: R$'))
print(f'A metade de {moeda(n)} é {moeda(metade(n))}')
print(f'O dobro de {moeda(n)} é {moeda(dobro(n))}')
print(f'Aumentando {moeda(10)}%, temos {moeda(aumentar(n, 10))}')
print(f'Reduzindo {moeda(13)}%, temos {moeda(diminuir(n, 13))}')
